version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: eabsensi_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: e_absensi_stikom
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: eabsensi_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=e_absensi_stikom
      - JWT_SECRET=supersecretkey_stikom
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: eabsensi_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
